# TODO: resolve requests=2.32.3 vs python=3.8 for tensorflow=1.* conflict
name: sa2c_code_torch
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pip
  - requests=2.32.3
  - fastparquet
  - pyarrow
  - mlflow=3.8.0
  - python-dotenv=1.0.1
  - pip:
      - torch==2.2.0+cu121
      - pytorch-lightning>=2.4.0
      - gdownload==0.1.1
      - pyyaml==6.0.1
      - transformers


